default_stages: [pre-push]
default_language_version:
  python: python3.12

repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v1.17.0
  hooks:
    - id: commitizen
      stages: [commit-msg]


- repo: local
  hooks:
    - id: check-build-files
      name: check-build-files
      entry: sh -c "pants tailor --check update-build-files --check ::"
      language: system
      pass_filenames: false

    - id: check-code-format-and-style
      name: check-code-format-and-style
      entry: sh -c "pants lint ::"
      language: system
      pass_filenames: false

    - id: check-typing
      name: check-typing
      entry: sh -c "pants --changed-since=main --changed-dependees=transitive check"
      language: system
      pass_filenames: false

    - id: run-tests
      name: run-tests
      entry: sh -c "pants test ::"
      language: system
      pass_filenames: false
