default_stages: [pre-push]
default_language_version:
  python: python3.12
repos:
- repo: local
  hooks:
    - id: check-commit-msg
      name: check-commit-msg
      entry: |
        sh -c "
          commit_msg=$1;
          echo $commit_msg;
          # if ! [[ $commit_msg =~ ^(feat|fix|docs|style|refactor|test|chore)(\\(.*\\))?:\\ .+ ]]; then
          #   echo 'ERROR: Commit message must follow Conventional Commits format (e.g., feat(scope): description)';
          #   exit 1;
          # fi
        "
      language: system
      stages: [commit-msg]
      
    - id: check-build-files
      name: check-build-files
      entry: sh -c "pants tailor --check update-build-files --check ::"
      language: system
      pass_filenames: false

    - id: check-code-format-and-style
      name: check-code-format-and-style
      entry: sh -c "pants lint ::"
      language: system
      pass_filenames: false

    - id: check-typing
      name: check-typing
      entry: sh -c "pants --changed-since=main --changed-dependees=transitive check"
      language: system
      pass_filenames: false

    - id: run-tests
      name: run-tests
      entry: sh -c "pants test ::"
      language: system
      pass_filenames: false
