default_stages: [pre-push]
default_language_version:
  python: python3.12

repos:
  - repo: git@github.com:commitizen-tools/commitizen.git
    rev: v3.31.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini, ./services]

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.2.0
    hooks:
      - id: flake8
        name: flake8
        pass_filenames: false
