default_stages: [pre-push]
default_language_version:
  python: python3.12

repos:
  - repo: git@github.com:commitizen-tools/commitizen.git
    rev: v3.31.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.16.1
    hooks:
      - id: mypy
        name: mypy
        args: [--config-file=mypy.ini]
        language_version: python3.12
        pass_filenames: false

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.2.0
    hooks:
      - id: flake8
        name: flake8
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
